{
 "title": "Meu Dash",
 "time": { "from": "2025-02-03T22:44:40.579Z", "to": "2025-02-03T22:48:58.270Z" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Tentativa de Acesso a Rotas Protegidas sem Permissão",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "access_denied_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cpu_load_1m", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de Rede TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "network_tx_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de Rede RX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "network_rx_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de Disco",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "disk_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Listagens de Usuários",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "list_users_total", "legendFormat": "__auto" }
   ]
  }
 ]
}