services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: always
    ports:
      - '4317:4317' # OTLP gRPC (usado pelo OpenTelemetry SDK)
      - '4318:4318' # OTLP HTTP
      - '8888:8888' # UI do OpenTelemetry Collector
      - '9464:9464' # Exposição de métricas para Prometheus
    volumes:
      - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: always
    ports:
      - '16686:16686' # UI do Jaeger
      - '14268:14268' # Coletor de traces HTTP
      - '14250:14250' # Coletor gRPC
      - '6831:6831/udp' # Recebimento de spans via UDP

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3001:3000'
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
