receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

  debug:
    verbosity: detailed

  otlp:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]  # Enviando os traces para o Jaeger e para os logs

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
